/** @jsxImportSource @emotion/react */
import { SearchOptions } from "@/components/atoms/SearchOptions";
import { SkeletonCustom } from "@/components/atoms/SkeletonCustom";
import { Content } from "@/components/molecules/Content";
import { useRepetitionSearch } from "@/helper/hooks/useRepetitionSearch";
// import { Searchbar } from "@/components/molecules/Searchbar";
// import { SearchFilter } from "@/components/molecules/SearchFilter";
import { css } from "@emotion/react";
import { Loader, NumberInput, Skeleton, Text } from "@mantine/core";
import { useDebouncedValue, useDisclosure } from "@mantine/hooks";
import { useQuery } from "@tanstack/react-query";
import { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import React from "react";

const Group = dynamic(() => import("@mantine/core").then((mod) => mod.Group), {
  ssr: false,
  loading: () => <Loader variant="dots" />,
});

const SegmentedControl = dynamic(
  () => import("@mantine/core").then((mod) => mod.SegmentedControl),
  { ssr: false, loading: () => <Loader variant="dots" /> }
);

const Searchbar = dynamic(
  () => import("@/components/molecules/Searchbar").then((mod) => mod.Searchbar),
  { ssr: false, loading: () => <Loader variant="dots" /> }
);

const SearchFilter = dynamic(
  () =>
    import("@/components/molecules/SearchFilter").then(
      (mod) => mod.SearchFilter
    ),
  { ssr: false, loading: () => <Loader variant="dots" /> }
);

type SearchData = {
  verse_key: string;
  document: string;
  similarity_score: number;
};

const Repetisi: NextPage = () => {
  const [search, setSearch] = React.useState<string>("");
  const [enabled, setEnabled] = React.useState<boolean>(false);
  const [opened, { open, close }] = useDisclosure(false);
  const [limit, setLimit] = React.useState<number>(10);
  const [focused, setFocused] = React.useState<string>("terjemah");

  const randomPlaceholder = ["Iman", "Takwa", "Allah", "Muhammad", "Puasa"];

  const { data, isError, isFetching } = useRepetitionSearch(
    focused,
    search,
    limit,
    enabled,
    setEnabled
  );

  React.useEffect(() => {
    console.log(data);
  }, [data]);

  return (
    <div
      css={css`
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        padding: 15px;
      `}
    >
      <Head>
        <title>Sequran - Mesin Pencari Quran</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>

      <Group
        position="center"
        style={{
          width: "100%",
          marginTop: "1rem",
          marginBottom: "1rem",
          display: "flex",
          flexDirection: "row",
        }}
      >
        <Searchbar
          css={css`
            width: 35%;
            @media (max-width: 768px) {
              width: 90%;
            }
          `}
          defaultValue={search}
          placeholder={randomPlaceholder[Math.floor(Math.random() * 5)]}
          onChange={(e) => setSearch(e.currentTarget.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              setEnabled(true);
            }
          }}
          setter={setEnabled}
        />
        {/* <SegmentedControl fullWidth data={SearchOptions} /> */}
        <SearchFilter
          opened={opened}
          open={open}
          close={close}
          limit={limit}
          setLimit={setLimit}
          additionalFilter={
            <>
              <Text size="sm" style={{ marginBottom: 10 }}>
                Fokus
              </Text>
              <SegmentedControl
                fullWidth
                data={SearchOptions}
                value={focused}
                onChange={setFocused}
              />
              <Text size="sm" style={{ marginBottom: 10, marginTop: 10 }}>
                Hasil yang ditampilkan
              </Text>
              <NumberInput
                placeholder="Number input"
                defaultValue={limit}
                min={10}
                max={30}
                onChange={(value) => setLimit(Number(value))}
              />
            </>
          }
        />
      </Group>

      {isFetching && <SkeletonCustom />}
      {/* <SkeletonCustom /> */}
      {isError && (
        <div style={{ textAlign: "center" }}>
          Error: Terjadi kesalahan pada server. Silakan coba beberapa saat lagi.
        </div>
      )}
      {/* Tampilkan data yang diterima dari server */}
      {!isFetching && data && Array.isArray(data.results) && (
        <div>
          <Text align="center">
            Menampilkan {data.results.length} hasil pencarian yang relevan
            dengan kata kunci
          </Text>
          <Text align="center" fw={500}>
            Fokus: {focused} | Total Ayat: {data.total_ayat} | Total Repetisi:{" "}
            {data.total_repetitions}
          </Text>

          {data?.results.map((item: any, index: number) => (
            <Content
              key={index}
              no={index + 1}
              verse={item.ayat_key}
              translation={item.terjemah}
              ayat={item.ayat}
              queryType="repetition-search"
            />
          ))}
        </div>
      )}
      {/* <Content /> */}
    </div>
  );
};

export default Repetisi;
